baseurl = "http://www.markfrodriguez.com/"
languageCode = "en-us"
title = "Mark F Rodriguez"
theme = "blackburn"
author = "Mark F Rodriguez"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = false
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "a more formal napkin"
  brand = "Macrod"
  googleAnalytics = "UA-54657218-1"
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "Jan 02, 2006, 15:04"
  
[permalinks]
  post = "/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-database fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Links"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 1
    identifier = "links"
    url = "/links/"
  [[menu.main]]
    name = "Search"
    pre = "<i class='fa fa-search fa-fw'></i>"
    weight = 1
    identifier = "search"
    url = "/search/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "@macrod"
  # facebook = "*"
  # instagram = "*"
  github = "markfrodriguez"
  # stackoverflow = "*"
  # linkedin = "*"

# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
