baseurl = "http://www.markfrodriguez.com/"
languageCode = "en-us"
title = "a more formal napkin"
theme = "internet-weblog"
paginate = 10
SectionPagesMenu = "main"
canonifyurls = false
# copyright = "&copy; 2018. All rights reserved."

[author]
  Handle = "Mark F Rodriguez"
  FirstName = "Mark"
  LastName = "Rodriguez"
  AboutPage = "/about"
  Location = "Fort Lauderdale, FL"
  # FlickrID = ""

[params]
  Description = "Internet weblog of Mark F Rodriguez."
  ShowCopyright = true
  RSSEnabled = true
  RSSSections = []
  RSSMicropostTitles = false

  # googleAnalytics = "UA-54657218-1"
  # CSS name for highlight.js
  # highlightjs = "androidstudio"
  dateFormat = "Jan 02, 2006, 15:04"

[permalinks]
  posts = "/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-database fa-fw'></i>"
    weight = 2
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Microposts"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 3
    identifier = "microposts"
    url = "/microposts/"
  [[menu.main]]
    name = "Search"
    pre = "<i class='fa fa-search fa-fw'></i>"
    weight = 4
    identifier = "search"
    url = "/search/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "@macrod"
  # facebook = "*"
  # instagram = "*"
  github = "markfrodriguez"
  # stackoverflow = "*"
  # linkedin = "*"
